-- 由 json_to_sql.py 自动生成，基于 data/historical_data.json
USE red_history;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE event_person;
TRUNCATE TABLE media;
TRUNCATE TABLE events;
TRUNCATE TABLE persons;
TRUNCATE TABLE locations;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P001', '柳条湖遗址', '辽宁省', 123.40666666666667, 41.806666666666665, '南满铁路途经地，日军在此自爆铁轨嫁祸中国军队，是九一八事变的导火索发生地，见证日本侵华开端。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P002', '华清池', '陕西省', 109.27472222222222, 34.348888888888894, '唐代皇家园林，1936年张学良、杨虎城在此扣押蒋介石，发动“兵谏”，最终促成西安事变和平解决，为抗日民族统一战线奠定基础');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P003', '卢沟桥', '北京市', 116.21361111111112, 39.85194444444445, '始建于金代的古石桥，横跨永定河，1937年日军以士兵失踪为借口挑起冲突，中国守军奋起抵抗，是全面抗战爆发的标志性地点。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P004', '上海抗战遗址群', '上海市', 121.48333333333333, 31.233333333333334, '涵盖多个抗战遗址，1932年、1937年两次大规模抗日战役在此打响，中国军队浴血奋战，打破日军“三个月灭亡中国”的妄想。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P005', '平型关战役遗址', '山西省', 113.85, 39.38333333333333, '晋东北咽喉要道，地势险要、易守难攻，1937年八路军第115师在此伏击日军精锐第5师团，取得全面抗战以来首次重大胜利。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P006', '侵华日军南京大屠杀遇难同胞纪念馆', '江苏省', 118.75, 32.05, '选址于南京大屠杀江东门集体屠杀遗址及遇难者丛葬地，见证1937年日军攻占南京后长达六周的反人类暴行，是铭记历史的核心场所。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P007', '台儿庄大战纪念馆', '山东省', 117.76666666666667, 34.55, '坐落于台儿庄古城内，1938年李宗仁指挥中国军队在此围歼日军，取得抗战以来正面战场最大胜利，纪念馆完整留存战役相关史料。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P008', '张家口抗日同盟军纪念馆', '河北省', 114.86666666666666, 40.8, '原为察哈尔省政府旧址，1933年冯玉祥在此组建察哈尔民众抗日同盟军，收复多伦等失地，是爱国力量团结抗日的重要见证地。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P009', '延安革命纪念馆', '陕西省', 109.6, 36.6, '抗日战争时期中共中央所在地，是敌后战场战略总后方，瓦窑堡会议确定抗日民族统一战线方针，延安整风运动统一全党思想。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P010', '皖南事变烈士陵园', '安徽省', 118.4, 30.433333333333334, '位于茂林镇山区，1941年新四军北移途中在此遭国民党军围攻，大部牺牲或被俘，陵园为纪念遇难新四军将士而建。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P011', '豫湘桂战役遗址群', '河南省，湖南省，广西省', 118.4, 30.433333333333334, '贯穿中原、华中、华南的交通要道集群，1944年日军为打通大陆交通线发动进攻，国民党军在此出现大规模败退，遗址留存战役相关痕迹。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P012', '日本东京湾密苏里号战舰（遗址关联）', '外国（日本）', 139.73333333333332, 35.65, '1945年9月2日，日本代表在此战舰上签署投降书，标志中国人民抗日战争暨世界反法西斯战争正式结束，是抗战胜利的核心见证地。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P013', '瓦窑堡会议旧址', '陕西省', 109.78333333333333, 37.016666666666666, '1935年中共中央在此召开瓦窑堡会议，批判“左”倾关门主义，确定建立抗日民族统一战线的策略方针，为第二次国共合作奠定理论基础。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P014', '徐州会战纪念馆', '江苏省', 117.26666666666667, 34.266666666666666, '以徐州为中心的大规模防御战，台儿庄战役是其中关键战役，纪念馆展示了中国军队阻击日军、消耗其有生力量的抗战史实。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P015', '武汉会战遗址群', '湖北省', 114.28333333333333, 30.583333333333332, '1938年中国军队投入百万兵力在此展开激战，毙伤日军近4万人，战后抗战进入战略相持阶段，遗址群留存大量战场遗迹。');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P016', '伪满洲国皇宫旧址', '吉林省', 125.32388888888889, 43.90694444444444, '1932-1945 年溥仪充当傀儡皇帝的居所，分内外廷，见证日本殖民统治');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P017', '长城抗战遗址群', '河北省', 118.5, 40.18333333333333, '1933 年中国军队在喜峰口、古北口阻击日军，第 29 军大刀队重创敌人');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P018', '一二・九运动相关纪念地', '北京市', 116.38333333333334, 39.9, '依托北平学生游行路线与历史资料建成，展示 1935 年爱国学生救亡运动历程');
INSERT INTO locations (id, name, province, longitude, latitude, description) VALUES ('P019', '百团大战纪念馆（碑）', '山西省', 113.5, 37.833333333333336, '1940 年八路军在此指挥百团大战，纪念馆陈列战役文物与史料，纪念碑镌刻参战部队名称');

INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R001', '张学良', '国民革命军陆军一级上将，东北军总司令', '东北军阀张作霖长子，人称“少帅”。九一八事变后因执行不抵抗政策遭诟病，后为促成抗日统一战线，与杨虎城发动西安事变，促成国共第二次合作，后被蒋介石长期软禁。', '1901-06-03', '2001-10-14');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R002', '杨虎城', '国民革命军陆军二级上将，第十七路军总指挥', '出身农民起义军，后归附国民政府，坚守抗日立场。与张学良联合发动西安事变，劝谏蒋介石联共抗日。事变后被迫辞职出国，回国后遭囚禁，1949年被国民党特务杀害。', '1893-11-26', '1949-09-06');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R003', '佟麟阁', '国民革命军陆军二级上将，第 29 军副军长', '早年投身军旅，跟随冯玉祥征战，后任第29军副军长。七七事变爆发后，坚守北平南苑阵地，率部奋勇抗击日军，1937年7月28日壮烈殉国，是全面抗战以来首位牺牲的高级将领。', '1892-10-29', '1937-07-28');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R004', '赵登禹', '国民革命军陆军中将，第 29 军第 132 师师长', '出身行伍，擅长近战和大刀战术，长城抗战中率部取得喜峰口大捷。七七事变后，在北平南苑战斗中，身先士卒抗击日军，不幸中弹牺牲，牺牲后被追赠上将军衔。', '1898-05-16', '1937-07-28');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R005', '林彪', '八路军第 115 师师长', '黄埔军校一期毕业生，无产阶级革命家、军事家。全面抗战爆发后，率领八路军第115师取得平型关大捷，打破日军不可战胜的神话，后长期在敌后领导抗日游击战争。', '1907-12-05', '1971-09-13');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R006', '聂荣臻', '八路军第 115 师副师长', '无产阶级革命家、军事家。抗战时期，协助林彪指挥平型关大捷，后率部创建晋察冀抗日根据地，开展敌后游击战争，为坚持华北抗战作出重要贡献。', '1899-12-29', '1992-05-14');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R007', '李宗仁', '国民革命军陆军一级上将，第五战区司令长官', '桂系军阀首领之一，坚持抗日主张。抗战时期任第五战区司令长官，指挥徐州会战，其中台儿庄战役歼灭日军2万余人，取得正面战场最大胜利，极大鼓舞全国抗战士气。', '1891-08-13', '1969-01-30');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R008', '彭德怀', '八路军副总司令', '无产阶级革命家、军事家。抗战时期任八路军副总司令，协助朱德指挥八路军开展敌后游击战争，1940年亲自指挥百团大战，大规模破袭日军交通线，沉重打击日军气焰。', '1898-10-24', '1974-11-29');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R009', '左权', '八路军副参谋长', '黄埔军校一期毕业生，杰出军事家。抗战时期任八路军副参谋长，协助彭德怀有条不紊地指挥作战，参与百团大战、黄崖洞保卫战等重要战役，1942年在反“扫荡”中壮烈殉国。', '1905-03-15', '1942-05-25');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R010', '叶挺', '新四军军长', '北伐名将，被誉为“铁军”指挥官。抗战时期出任新四军军长，领导华中敌后抗日游击战争。1941年皖南事变中被俘，身陷囹圄多年始终坚贞不屈，1946年获释后因飞机失事遇难。', '1896-09-10', '1946-04-08');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R011', '项英', '新四军副军长，中共中央东南局书记', '无产阶级革命家，长期从事工人运动和革命武装斗争。抗战时期任新四军副军长，协助叶挺领导新四军抗日。1941年皖南事变后，在突围途中被叛徒杀害，遗体后被安葬于江夏区青龙山。', NULL, '1941-03-12');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R012', '吉鸿昌', '察哈尔民众抗日同盟军第二军军长', '爱国将领，早年投身冯玉祥部队，坚决反对蒋介石的不抵抗政策。1933年参与组建察哈尔民众抗日同盟军，率部收复多伦等失地，后被国民党当局逮捕，1934年英勇就义，就义前高呼“我是中国人”。', '1895-10-18', '1934-11-24');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R013', '冯玉祥', '国民革命军陆军一级上将', '著名爱国将领，人称“基督将军”。多次反对蒋介石的独裁政策，积极主张抗日。1933年组建察哈尔民众抗日同盟军，领导抗日斗争，后参与淞沪会战等战事，1948年在回国途中因轮船失火遇难。', '1882-11-06', '1948-09-01');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R014', '蒋光鼐', '国民革命军第十九路军总指挥', '爱国将领，早年参加辛亥革命。1932年一·二八事变爆发后，任第十九路军总指挥，率部在上海奋勇抗击日军进攻，打破日军快速占领上海的企图，后因孤军无援被迫撤退。', '1888-12-01', '1967-06-08');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R015', '蔡廷锴', '国民革命军第十九路军军长', '出身贫苦农民家庭，后投身军旅。一·二八事变中，任第十九路军军长，与蒋光鼐并肩作战，指挥部队顽强抵抗日军，多次击退日军进攻，展现了中国军队的抗战决心。', '1892-04-15', '1968-04-25');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R016', '毛泽东', '中共中央主席，中央军委主席', '中国共产党、中国人民解放军和中华人民共和国的主要缔造者和领导人。抗战时期，提出持久战战略方针，主持召开瓦窑堡会议确立抗日民族统一战线政策，领导全国人民坚持敌后抗战。', '1893-12-26', '1976-09-09');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R017', '溥仪', '清朝末代皇帝，伪满洲国 “执政', '1912年退位，1931年九一八事变后，在日本扶持下于1932年建立伪满洲国，充当日本殖民统治的傀儡，出卖国家主权和民族利益，抗战胜利后被苏联俘获，后回国接受改造。', '1906-02-07', '1967-10-17');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R018', '谷寿夫', '日本第 6 师团师团长', '日本战犯，1937年率日本第6师团参加南京攻城战，进城后指挥部队实施惨无人道的大屠杀，残害大量中国平民和战俘。抗战胜利后被国民政府逮捕，1947年以战争罪、反人类罪被处决。', '1882-12-23', '1947-04-26');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R019', '松井石根', '日本华中方面军司令官', '日本战犯，早年参与侵华活动。1937年任日本华中方面军司令官，指挥淞沪会战和南京攻城战，纵容日军在南京实施大规模屠杀、强奸等暴行，战后被远东国际军事法庭判定为甲级战犯，1948年被执行绞刑。', '1878-07-27', '1948-12-23');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R020', '蒋介石', '国民党总裁、国民政府主席，抗日战争时期中国战区最高统帅', '原名蒋中正，早年留学日本，历任黄埔军校校长、国民政府主席等职。抗日战争时期领导正面战场抗战，先后指挥淞沪会战、徐州会战、武汉会战等战役；内战失败后退守台湾，1975 年在台北逝世。', '1887-10-31', '1975-04-05');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R021', '宋哲元', '国民党爱国将领，二十九军军长，长城抗战、七七事变主要指挥官', '西北军将领，1933 年率部参加长城抗战，取得喜峰口大捷；1937 年七七事变中，率二十九军在卢沟桥抵抗日军进攻，是全面抗战爆发的关键人物之一，1940 年病逝。', NULL, '1940-04-05');
INSERT INTO persons (id, name, role, description, birth_date, death_date) VALUES ('R022', '傅作义', '国民党爱国将领，绥远抗战、平津战役主要指挥官，后率部起义', '晋绥军将领，抗日战争时期率部参加绥远抗战、百团大战等战役，取得五原大捷；1949 年平津战役中率部接受和平改编，保护北平古城，新中国成立后担任水利部部长等职。', '1895-06-27', '1974-04-19');

INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E001', '九一八事变', '1931-09-18', '日军侵华开端', '日军蓄意制造事端，侵占中国东北三省', '日本关东军炸毁南满铁路柳条湖段，嫁祸中国军队，突袭东北军北大营。张学良执行 “不抵抗政策”，东北军撤入关内，沈阳次日沦陷，数月内东北三省被占。', NULL, '中国抗日战争起点，揭开世界反法西斯战争序幕', 'P001');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E002', '一・二八事变', '1932-01-28', '正面战场局部抗战', '日军进攻上海，十九路军奋起抵抗', '日军借口僧侣事件进攻上海，国民革命军第十九路军自发奋起反击，多次击退日军进攻。后因寡不敌众且援军不足，被迫撤退，双方签订《淞沪停战协定》。', NULL, '打破日军快速占领上海的企图，推动抗日救亡运动', 'P004');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E003', '伪满洲国建立', '1932-03-01', '日本殖民傀儡政权', '日本扶植傀儡政权，殖民统治东北', '日本在东北扶植清朝末代皇帝溥仪，建立 “满洲国” 傀儡政权，以 “王道乐土” 为幌子，对东北人民实施残酷的政治压迫、经济掠夺和文化奴役。', NULL, '日本妄图永久侵占东北的殖民手段，遭国际反对', 'P016');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E004', '长城抗战', '1933-01-01', '正面战场防御战', '中国军队坚守长城，阻击侵华日军', '日军攻占山海关后向长城各关口进犯，中国军队第 29 军等部在喜峰口、古北口等地顽强抵抗，以大刀队夜袭日军，重创敌人。后防线被突破，签订《塘沽协定》。', NULL, '展现中国军队保家卫国血性，推动救亡运动高涨', 'P017');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E005', '察哈尔民众抗日同盟军成立', '1933-05-26', '抗日武装组建', '组建抗日同盟军，收复多伦等失地', '冯玉祥联合爱国将领在张家口成立同盟军，兵力达 10 万余人，接连收复康保、宝昌、多伦等失地，打击日军气焰。后遭国民政府压迫，同盟军被迫解散。', NULL, '体现抗日力量团结，沉重打击日军侵略势力', 'P008');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E006', '一二・九运动', '1935-12-09', '爱国学生救亡运动', '学生游行示威，反对华北自治阴谋', '面对日本策划的 “华北自治”，北平数千名学生高呼 “停止内战，一致抗日” 口号游行，遭军警镇压。运动迅速席卷全国，各地纷纷响应。', NULL, '揭露日本侵华阴谋，促进中华民族觉醒', 'P018');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E007', '瓦窑堡会议', '1935-12-17', '中共重要会议', '制定抗日民族统一战线的策略方针', '中共中央召开会议，分析华北事变后的形势，批判 “左” 倾关门主义，确定建立抗日民族统一战线的策略方针，为第二次国共合作奠定理论基础。', NULL, '标志中共政治路线成熟，推动抗日力量联合', 'P013');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E008', '西安事变', '1936-12-12', '兵谏事件', '扣押蒋介石，迫其停止内战联共抗日', '张学良、杨虎城为劝谏蒋介石放弃 “攘外必先安内” 政策，于西安扣押蒋介石。经中共调停，事变和平解决，蒋介石同意联共抗日。', NULL, '结束十年内战，抗日民族统一战线初步形成', 'P002');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E009', '七七事变（卢沟桥事变）', '1937-07-07', '全面抗战爆发标志', '日军挑衅，中国守军奋起全面抵抗', '日军以士兵失踪为由要求进宛平城搜查，遭拒后炮轰卢沟桥。第 29 军官兵奋起反击，佟麟阁、赵登禹壮烈殉国，战争迅速蔓延全国。', NULL, '日本全面侵华开端，中国进入全民族抗战', 'P003');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E010', '淞沪会战', '1937-08-13', '正面战场大规模会战', '中日大规模会战，粉碎日军速胜妄想', '中国军队投入 70 余万兵力，在上海与日军展开三个月激战，多次击退日军进攻，毙伤日军 4 万余人。后因战略调整，被迫撤退，上海沦陷。', NULL, '打破 “三个月灭亡中国” 的狂妄计划', 'P004');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E011', '平型关大捷', '1937-09-25', '敌后战场首次大捷', '八路军伏击日军，取得抗战首次大捷', '八路军第 115 师在平型关设伏，歼灭日军精锐第 5 师团 1000 余人，击毁汽车百余辆，缴获大批物资。这是全面抗战以来中国军队首次重大胜利。', NULL, '打破 “日军不可战胜” 神话，鼓舞全国信心', 'P005');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E012', '南京大屠杀', '1937-12-13', '日军侵华反人类暴行', '日军在南京实施大规模屠杀与暴行', '日军攻占南京后，六周内对中国平民和战俘进行惨无人道的屠杀、强奸、纵火、抢劫，遇难人数超过 30 万，是震惊世界的反人类罪行。', NULL, '日军侵华暴行铁证，警示后人铭记历史', 'P006');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E013', '台儿庄战役', '1938-03-16', '正面战场重大胜利', '中国军队围歼日军，获抗战以来大捷', '李宗仁指挥中国军队在台儿庄地区围歼日军矶谷师团，激战月余，歼灭日军 2 万余人，缴获大批武器装备，是抗战以来正面战场最大胜利。', NULL, '增强全国抗战信念，遏制日军进攻势头', 'P007');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E014', '徐州会战', '1938-01-01', '正面战场大规模会战', '阻击日军打通津浦线，掩护主力转移', '中国军队以徐州为中心展开防御，台儿庄战役是其中关键一战。后因日军重兵合围，中国军队主动突围，徐州沦陷，但打乱了日军作战计划。', NULL, '消耗日军有生力量，为武汉会战争取时间', 'P014');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E015', '武汉会战', '1938-06-11', '正面战场战略防御战', '大规模会战，抗战进入战略相持阶段', '中国军队投入百万兵力，在武汉外围与日军展开激战，毙伤日军近 4 万人。后为保存实力主动撤退，武汉沦陷。此战使日军兵力严重消耗，无力发动大规模进攻。', NULL, '标志抗战进入战略相持阶段', 'P015');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E016', '百团大战', '1940-08-20', '敌后战场大规模破袭战', '八路军发动破袭战，打击日军囚笼政策', '八路军出动 105 个团约 20 万人，对华北日军交通线、据点展开大规模破袭，破坏铁路公路数千公里，毙伤日伪军 4 万余人，缴获大量物资。', NULL, '沉重打击日军气焰，振奋全国军民意志', 'P019');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E017', '皖南事变', '1941-01-04', '国共摩擦事件', '国民党围攻新四军，制造反共摩擦', '新四军军部及所属部队 9000 余人北移时，遭国民党军 8 万余人围攻。新四军浴血奋战，除 2000 余人突围外，大部牺牲或被俘，叶挺被俘，项英牺牲。', NULL, '暴露国民党反共阴谋，中共维护统一战线', 'P010');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E018', '延安整风运动', '1941-05-01', '中共党内思想整顿', '整顿党风学风文风，统一全党思想', '中共中央开展整风运动，反对主观主义、宗派主义、党八股，树立实事求是的思想路线，实现全党思想上、政治上、组织上的空前团结。', NULL, '为抗战和革命胜利奠定思想基础', 'P009');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E019', '豫湘桂战役', '1944-04-01', '正面战场溃败战役', '日军发动攻势，国民党军大规模败退', '日军为打通大陆交通线发动战役，国民党军因指挥失当、士气低落，在八个月内丢失大片国土，损失兵力 50 余万。但日军也付出惨重代价，无力持续进攻。', NULL, '暴露国民党消极抗日弊端，推动民主运动高涨', 'P011');
INSERT INTO events (id, title, date, category, description, background, process, impact, location_id) VALUES ('E020', '日本无条件投降', '1945-08-15', '抗战胜利标志', '日本宣布投降，中国人民抗战胜利结束', '1945 年 8 月 15 日，日本天皇裕仁发布《终战诏书》宣布无条件投降。9 月 2 日，日本代表在 “密苏里号” 战舰签署投降书，中国人民 14 年抗战正式结束。', NULL, '中国近代反侵略首次完全胜利，提升国际地位', 'P012');

INSERT INTO event_person (event_id, person_id) VALUES ('E001', 'R001');
INSERT INTO event_person (event_id, person_id) VALUES ('E002', 'R014');
INSERT INTO event_person (event_id, person_id) VALUES ('E002', 'R015');
INSERT INTO event_person (event_id, person_id) VALUES ('E003', 'R017');
INSERT INTO event_person (event_id, person_id) VALUES ('E004', 'R021');
INSERT INTO event_person (event_id, person_id) VALUES ('E004', 'R022');
INSERT INTO event_person (event_id, person_id) VALUES ('E005', 'R012');
INSERT INTO event_person (event_id, person_id) VALUES ('E005', 'R013');
INSERT INTO event_person (event_id, person_id) VALUES ('E007', 'R016');
INSERT INTO event_person (event_id, person_id) VALUES ('E008', 'R001');
INSERT INTO event_person (event_id, person_id) VALUES ('E008', 'R002');
INSERT INTO event_person (event_id, person_id) VALUES ('E008', 'R020');
INSERT INTO event_person (event_id, person_id) VALUES ('E009', 'R003');
INSERT INTO event_person (event_id, person_id) VALUES ('E009', 'R004');
INSERT INTO event_person (event_id, person_id) VALUES ('E010', 'R013');
INSERT INTO event_person (event_id, person_id) VALUES ('E010', 'R019');
INSERT INTO event_person (event_id, person_id) VALUES ('E010', 'R020');
INSERT INTO event_person (event_id, person_id) VALUES ('E011', 'R005');
INSERT INTO event_person (event_id, person_id) VALUES ('E011', 'R006');
INSERT INTO event_person (event_id, person_id) VALUES ('E012', 'R018');
INSERT INTO event_person (event_id, person_id) VALUES ('E012', 'R019');
INSERT INTO event_person (event_id, person_id) VALUES ('E013', 'R007');
INSERT INTO event_person (event_id, person_id) VALUES ('E014', 'R007');
INSERT INTO event_person (event_id, person_id) VALUES ('E015', 'R020');
INSERT INTO event_person (event_id, person_id) VALUES ('E016', 'R008');
INSERT INTO event_person (event_id, person_id) VALUES ('E016', 'R009');
INSERT INTO event_person (event_id, person_id) VALUES ('E017', 'R010');
INSERT INTO event_person (event_id, person_id) VALUES ('E017', 'R011');
INSERT INTO event_person (event_id, person_id) VALUES ('E018', 'R016');
INSERT INTO event_person (event_id, person_id) VALUES ('E019', 'R020');
INSERT INTO event_person (event_id, person_id) VALUES ('E020', 'R016');
INSERT INTO event_person (event_id, person_id) VALUES ('E020', 'R020');